### ISSUE TITLE
You should submit this plugin to the WP repo

### ISSUE THREAD

**Issue by lukecav** [dannyvankooten/my-precious#1]
https://codex.wordpress.org/Plugin_Submission_and_Promotion

**Comment by dannyvankooten** [comment]
Hi @lukecav,

Feel free to take the source from GitHub and submit the plugin to WordPress.org under your name, I have no interest to do so at this time.

Cheers.

**Comment by lukecav** [comment]
@dannyvankooten

Okay will do thanks.
